<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_UBE (Usaha Besar)</name>
   <tag></tag>
   <elementGuidId>1f904c76-c0be-41c3-866a-17c89ceaa174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id = 'select2-merchant_criteria-ot-result-4klm-UBE' and (text() = 'UBE (Usaha Besar)' or . = 'UBE (Usaha Besar)')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d7e55640-71d3-4a27-a2b9-28a3c4d4fdc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>7603829e-6292-42e6-9771-b7b811ecb406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-merchant_criteria-ot-result-4klm-UBE</value>
      <webElementGuid>ea5409d8-b6b2-4a4d-9e5d-fd00576a160b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7eb3e342-bbb5-4a98-85cc-32592309e90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>995cd9ed-ea0d-4d20-b86c-7d9c5431a63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-merchant_criteria-ot-result-4klm-UBE</value>
      <webElementGuid>960233dd-7338-49b8-b8fb-45be56474955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UBE (Usaha Besar)</value>
      <webElementGuid>f9100098-5766-4963-9f3f-c00c0a9a3d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/span[@class=&quot;select2-container select2-container--bootstrap select2-container--open&quot;]/span[@class=&quot;select2-dropdown select2-dropdown--below&quot;]/span[@class=&quot;select2-results&quot;]/ul[@id=&quot;select2-merchant_criteria-ot-results&quot;]/li[@id=&quot;select2-merchant_criteria-ot-result-4klm-UBE&quot;]</value>
      <webElementGuid>d49dfb91-b81f-4b2b-aec7-df8e38dbec18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-merchant_criteria-ot-result-4klm-UBE' and (text() = 'UBE (Usaha Besar)' or . = 'UBE (Usaha Besar)')]</value>
      <webElementGuid>1367f836-66c9-40fb-a4a7-4cef39ff09c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
