<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Aksi_btn btn-sm btn-info text-white</name>
   <tag></tag>
   <elementGuidId>c8b11b7c-6b82-4155-af97-0a679718fa1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//html/body/div[4]/div/div/div[2]/table/tbody/tr[9]/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2) > a.btn.btn-sm.btn-info.text-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>acd465d5-32a4-4e75-928e-79a9dc2c6ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sb-batpanel.batpay.id/saldo-management/70/show</value>
      <webElementGuid>d8dee542-6ac2-48a6-a512-3a9a02db9c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>show</value>
      <webElementGuid>57bfef9d-47d8-42b9-88ae-777e88e1520f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>400fb008-2c17-4f5f-9ea0-de3f3a650b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>9d946681-9670-455b-97fe-01b0a18fef7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Lihat Detail Pengajuan</value>
      <webElementGuid>7aa77d23-71c0-4216-b2d2-3df4bfdd25c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-info text-white</value>
      <webElementGuid>fa1c3107-71c8-4609-bc0f-e5adee7d24d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pace-done pace-done pace-running app aside-menu-fixed sidebar-lg-show modal-open&quot;]/div[@class=&quot;modal fade dtr-bs-modal show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/table[@class=&quot;table table-striped mb-0&quot;]/tbody[1]/tr[9]/td[2]/a[@class=&quot;btn btn-sm btn-info text-white&quot;]</value>
      <webElementGuid>9d01a8e0-7915-4cd6-b233-1a47b8402688</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://sb-batpanel.batpay.id/saldo-management/70/show')])[2]</value>
      <webElementGuid>da0d4a23-7c5e-4aa1-99e7-76a8fd5b13df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>47f88a2b-7170-4f9b-b4c9-1ce3eba9cd8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sb-batpanel.batpay.id/saldo-management/70/show' and @title = 'Lihat Detail Pengajuan']</value>
      <webElementGuid>0a37a26c-dafc-4e14-9dbe-788baced19c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
