<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aksi_btn btn-sm btn-danger mr-2</name>
   <tag></tag>
   <elementGuidId>de02b0b7-7fba-452e-9317-fa7f99ce4103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//html/body/div[4]/div/div/div[2]/table/tbody/tr[9]/td[2]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2) > button.btn.btn-sm.btn-danger.mr-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dcc53a44-da83-407d-956d-132356bb5d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1d10e2d7-7f75-41fe-a35c-44f126308892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target-id</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>62dc588e-22d8-4608-8ebf-a468efd91be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-step</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4e674c9e-211c-4ae3-bcc2-a3a78d8a9505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-approval-flow-detail-id</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>4975ae83-74d0-4ef4-8ef1-d663d1fa72ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-module-approval-flow-id</name>
      <type>Main</type>
      <value>239</value>
      <webElementGuid>b0f1f234-8a8b-4d77-b855-aeaa06834ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>reject</value>
      <webElementGuid>879ff686-e2bc-4742-9bd1-ce7358e1e2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attachment-action</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7fbc2484-eb73-4c32-b584-fcb7297ad4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-using-attachment</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ddf6df0a-d32f-4875-8605-286ed99c7cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attachment-mandatory</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>82ae00a0-bda7-4e5b-9b80-54806189612d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>btn-approval</value>
      <webElementGuid>c74b000a-3737-4489-afb0-5fbc0f328880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-danger mr-2</value>
      <webElementGuid>702085e1-7b4c-467c-80f9-6ce247a3c919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>02846734-4376-45af-a671-92baad7db2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>4220c09f-63ea-4ada-baf3-e7e2f135905d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tolak Pengajuan</value>
      <webElementGuid>95d9f346-7023-42f4-8a3c-97e6a1df656e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pace-done pace-done pace-running app aside-menu-fixed sidebar-lg-show modal-open&quot;]/div[@class=&quot;modal fade dtr-bs-modal show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/table[@class=&quot;table table-striped mb-0&quot;]/tbody[1]/tr[9]/td[2]/button[@class=&quot;btn btn-sm btn-danger mr-2&quot;]</value>
      <webElementGuid>e4a1f7df-3d21-4370-bc86-d4e426a1e446</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[27]</value>
      <webElementGuid>041c8a3f-a488-40aa-ba1a-620fd9529f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/button[2]</value>
      <webElementGuid>09c4bba4-c6c4-455b-9b3a-879b19e2e641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Tolak Pengajuan']</value>
      <webElementGuid>7de8470f-2d21-4a41-a4b2-92513bfda75a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
