<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_btn btn-sm btn-success mr-2</name>
   <tag></tag>
   <elementGuidId>1e28602b-b9ac-4508-8ef0-072124d9ec19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2) > button.btn.btn-sm.btn-success.mr-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>33d16893-c15a-4c76-9b46-d7ab3d26d1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21bbd36e-1a8c-4ef8-a9a8-2c473b9feec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target-id</name>
      <type>Main</type>
      <value>68</value>
      <webElementGuid>0f9ac288-68e6-42c6-8714-dd6282e64c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-step</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d6eb8eb3-1ce2-4c02-b14d-ab9616beff2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-approval-flow-detail-id</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>40af73e3-8c74-4666-a8cc-10283b7efd6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-module-approval-flow-id</name>
      <type>Main</type>
      <value>235</value>
      <webElementGuid>20789833-2bd1-45de-89b0-83fb45ba468c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>approve</value>
      <webElementGuid>5b495ad3-7755-4cee-bcbb-2e2d367eff0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attachment-action</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c32f0fa8-b1df-4f33-973b-0f1ad6c7498a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-using-attachment</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>919ffe27-1c02-46a7-bd4e-477e5248d87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attachment-mandatory</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b34dcf91-e8ed-496a-b0c5-1e426a151e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>btn-approval</value>
      <webElementGuid>e4a24928-1d18-45cb-bcaf-8382a9a335b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-success mr-2</value>
      <webElementGuid>f29db20e-07a6-4764-83ff-831efebe3689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>909a6257-2281-4294-bdfc-a728c02f3b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>fd701acb-14e3-4480-bcd6-9b7257d3eb3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Setujui Pengajuan</value>
      <webElementGuid>02fe68c8-390d-4bb7-84b9-75e067f8ebe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pace-done pace-done pace-running app aside-menu-fixed sidebar-lg-show modal-open&quot;]/div[@class=&quot;modal fade dtr-bs-modal show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/table[@class=&quot;table table-striped mb-0&quot;]/tbody[1]/tr[9]/td[2]/button[@class=&quot;btn btn-sm btn-success mr-2&quot;]</value>
      <webElementGuid>c3a6a2e9-f9f8-4956-a34f-3547dd19f10f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
      <webElementGuid>634f6a9e-28b2-4c96-8e53-0a4b08d6f8ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/button</value>
      <webElementGuid>5f474dcd-f504-479c-8cfa-153de6758434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Setujui Pengajuan']</value>
      <webElementGuid>490edd9f-b9d8-444b-839a-f36fac834695</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
