<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_btn btn-sm btn-success mr-2</name>
   <tag></tag>
   <elementGuidId>1e28602b-b9ac-4508-8ef0-072124d9ec19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div/div/div[2]/table/tbody/tr[9]/td[2]/button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2) > button.btn.btn-sm.btn-success.mr-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5b174a8b-6ac1-44ec-955b-0aa5514e2bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>45848770-dc7b-4829-a69d-90f7d9cd8917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target-id</name>
      <type>Main</type>
      <value>68</value>
      <webElementGuid>a1c3e5e1-3aae-410a-8d60-74bcd4997322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-step</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8dc7481f-0362-4b79-ab4b-c7f13a9c0c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-approval-flow-detail-id</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>5d5b5545-eeea-4d9a-b7de-b4c51f06807e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-module-approval-flow-id</name>
      <type>Main</type>
      <value>235</value>
      <webElementGuid>54f95c81-2f3d-41ea-8908-9aa2318f87c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>approve</value>
      <webElementGuid>5ad1dfdc-8dc0-466a-abb9-bd9216f8f1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attachment-action</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>84da266f-6e06-481c-9991-5eaf3e78af9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-using-attachment</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5065f2bf-0564-424a-98a2-76b9d41c946f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attachment-mandatory</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>20e83be1-3a95-428e-ab65-628f06a12b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>btn-approval</value>
      <webElementGuid>2ec9851e-c5e5-4b55-a02b-4f806a136e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-success mr-2</value>
      <webElementGuid>371623a4-ad78-407d-952f-fac823fe4224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>79a10cec-b7bc-4668-ad83-8e2ee390692c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>c8d05587-6a1f-4f52-a724-d85785fb4768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Setujui Pengajuan</value>
      <webElementGuid>c5220580-9f07-4172-981a-6a3a795c85a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pace-done pace-done pace-running app aside-menu-fixed sidebar-lg-show modal-open&quot;]/div[@class=&quot;modal fade dtr-bs-modal show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/table[@class=&quot;table table-striped mb-0&quot;]/tbody[1]/tr[9]/td[2]/button[@class=&quot;btn btn-sm btn-success mr-2&quot;]</value>
      <webElementGuid>14e3965b-37e2-497c-a981-a30b9b667755</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
      <webElementGuid>679212e9-bd5b-48fe-a32a-e5a0090765f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/button</value>
      <webElementGuid>0cb26aef-4231-4481-885d-3e251ecd2958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Setujui Pengajuan']</value>
      <webElementGuid>7f761dc3-0b21-41e5-9669-0c66ca49241e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
