<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_img-avatar</name>
   <tag></tag>
   <elementGuidId>c890c9e6-31d7-4ab6-ad66-60b432f7f100</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Rike - Staff Finance']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-avatar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7536894f-9084-44b0-9deb-5804b33b2cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-avatar</value>
      <webElementGuid>5d17da3b-a9bf-4b06-b87f-369478f8ed0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.gravatar.com/avatar/efef0e95603dc8d5fb26e1f1f1ffb9a8.jpg?s=80&amp;d=blank&amp;r=g</value>
      <webElementGuid>0eedef54-e56f-41dc-bc95-7ca1acb12b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Rike - Staff Finance</value>
      <webElementGuid>7e9e5e86-62e9-4a2a-9a31-be76a04d2b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.style.display='none'</value>
      <webElementGuid>24df2e4b-a576-45b4-a303-bc8beb22127e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pace-done pace-done pace-running app aside-menu-fixed sidebar-lg-show&quot;]/header[@class=&quot;app-header navbar navbar-color bg-header border-0&quot;]/ul[@class=&quot;nav navbar-nav ml-auto&quot;]/li[@class=&quot;nav-item dropdown pr-4&quot;]/a[@class=&quot;nav-link&quot;]/img[@class=&quot;img-avatar&quot;]</value>
      <webElementGuid>6fde3cf5-23b7-4bcd-ae8f-235b4fdb136c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Rike - Staff Finance']</value>
      <webElementGuid>dcad76f5-224d-4664-bfba-70ab651f5cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/img</value>
      <webElementGuid>fa66fd0c-caf8-4624-811d-f0ebee505d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.gravatar.com/avatar/efef0e95603dc8d5fb26e1f1f1ffb9a8.jpg?s=80&amp;d=blank&amp;r=g' and @alt = 'Rike - Staff Finance']</value>
      <webElementGuid>256a6432-44ca-4db1-998c-ae9e1d19e5f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
