<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_img-avatar</name>
   <tag></tag>
   <elementGuidId>c890c9e6-31d7-4ab6-ad66-60b432f7f100</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/header/ul[2]/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-avatar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>559fe44b-291e-463d-aeb1-55b6b822f805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-avatar</value>
      <webElementGuid>62fcdb6c-09fe-4d9c-9da1-5c50b8e5760f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.gravatar.com/avatar/efef0e95603dc8d5fb26e1f1f1ffb9a8.jpg?s=80&amp;d=blank&amp;r=g</value>
      <webElementGuid>199a9fce-ef8f-4289-8a94-20955e4e38af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Rike - Staff Finance</value>
      <webElementGuid>53bd0898-2fb5-40e5-8040-fe770b73bfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.style.display='none'</value>
      <webElementGuid>e95304cd-b39f-49e4-9e55-bfd4711b4e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pace-done pace-done pace-running app aside-menu-fixed sidebar-lg-show&quot;]/header[@class=&quot;app-header navbar navbar-color bg-header border-0&quot;]/ul[@class=&quot;nav navbar-nav ml-auto&quot;]/li[@class=&quot;nav-item dropdown pr-4&quot;]/a[@class=&quot;nav-link&quot;]/img[@class=&quot;img-avatar&quot;]</value>
      <webElementGuid>232b6536-8e3f-401e-aeb8-2f4c940b3288</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Rike - Staff Finance']</value>
      <webElementGuid>c81ea595-211e-4ddd-be21-9d2bec72614d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/img</value>
      <webElementGuid>7ac099b3-ef90-4767-823e-d5ceb4b01597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.gravatar.com/avatar/efef0e95603dc8d5fb26e1f1f1ffb9a8.jpg?s=80&amp;d=blank&amp;r=g' and @alt = 'Rike - Staff Finance']</value>
      <webElementGuid>68731f6f-ed5f-4ea0-8ba8-ec20ebb03444</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
