<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Atur Saldo_form-control</name>
   <tag></tag>
   <elementGuidId>36284244-f886-4941-a9bc-05e7a4c509fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce70a65a-47ce-44ec-9d6b-11a1ae23955a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>1abc7469-cf28-4d3e-b08d-b2d2bd248657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b01b9efc-a9ed-48e6-8d66-a1f112a04b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari...</value>
      <webElementGuid>0ba32a79-3a32-4b09-859d-74ff6eda1703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>crudTable</value>
      <webElementGuid>364fd90f-a31d-44d5-afb7-7f0588704a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;crudTable_filter&quot;)/label[1]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>48cd3f62-36ce-4035-8c65-70458e882f3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='search']</value>
      <webElementGuid>7c9cac96-4815-4934-92b6-57b658359145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='crudTable_filter']/label/input</value>
      <webElementGuid>b83c14bb-b08c-4a5b-bdc9-448d8b2ceb6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>299b3316-b404-4f28-ae35-a77fa3faee8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Cari...']</value>
      <webElementGuid>ad3ff79e-f62b-4ded-8228-d0da7ed91099</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
