<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Tolak</name>
   <tag></tag>
   <elementGuidId>e3d53811-0a68-4aae-8c8e-5fc6834c1cfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//html/body/div[2]/main/div[2]/div/div/nav/div/ul/li[2]/div/div/span[2]/span/span[2]/ul/li[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-filter_status-result-31ei-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>cba12d0d-5996-4ef2-8785-8da940eca4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option</value>
      <webElementGuid>f38a2dd9-dbd1-4b97-8139-c5df668e026e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-filter_status-result-31ei-2</value>
      <webElementGuid>02e3d93f-24f7-4c9e-927d-0f40720fbf2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>24538d6f-cbe4-468a-86c7-ba89ae6687dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1f1884bd-7406-4fdc-9348-c39a651b978e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-filter_status-result-31ei-2</value>
      <webElementGuid>4d50ff93-f427-460f-8e98-0994535366dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							Tolak
						</value>
      <webElementGuid>b3f67fb0-c4d4-45dc-a837-bca1a60ffd9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-filter_status-result-31ei-2&quot;)</value>
      <webElementGuid>0b2b152f-d477-4a94-84d5-b710663ed2ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-filter_status-result-31ei-2']</value>
      <webElementGuid>a13b1dbe-7be7-40cd-ba66-8ac0bb2aa5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-filter_status-results']/li[4]</value>
      <webElementGuid>9b409697-81d7-4186-ba62-a6c0246143a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li[4]</value>
      <webElementGuid>07fa78f3-21f7-4fad-91a5-31b8c3abf654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-filter_status-result-31ei-2' and (text() = '
							Tolak
						' or . = '
							Tolak
						')]</value>
      <webElementGuid>53aba69b-e28b-4af5-8262-fe27568eca60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
