<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_2</name>
   <tag></tag>
   <elementGuidId>c21b41cb-888b-4440-afc6-f9358285fe52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/main/div[2]/div/div/div[2]/div[2]/div/table/tbody/tr[2]/td[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/main/div[2]/div/div/div[2]/div[2]/div/table/tbody/tr[2]/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/main/div[2]/div/div/div[2]/div[2]/div/table/tbody/tr[2]/td[1]</value>
      <webElementGuid>c4622caf-51fc-4b22-9bd2-41e4668543c4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
