<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Komentar_remark</name>
   <tag></tag>
   <elementGuidId>48dc2cb2-06d5-4502-98b3-e9e6c0c38217</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#remark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='remark']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8cfc498c-f4ac-46bb-a083-fbff342c3fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>remark</value>
      <webElementGuid>6668eb12-1697-4d6e-8302-0eb2cccfbf0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remark</value>
      <webElementGuid>3382d269-48d0-413c-9e9a-54c2284fcfe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a9851d8b-ddc0-42dd-9839-60f070e38023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isikan komentar disini</value>
      <webElementGuid>bc1c7ace-0174-4b1a-ae6a-f392b6f2426e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remark&quot;)</value>
      <webElementGuid>9e62085b-0a8d-49ef-9e9d-27950ff99eb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='remark']</value>
      <webElementGuid>00ea3df1-cbaf-48c8-8e81-2ce90fa51d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-list-approval']/div/div/div[2]/div[2]/textarea</value>
      <webElementGuid>5649eda9-8e91-474d-935d-2ba7efb12af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>504594c9-7282-4c89-9656-54d5a251617a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'remark' and @id = 'remark' and @placeholder = 'Isikan komentar disini']</value>
      <webElementGuid>626850a2-bf2b-4ebe-951d-7b429baaaf8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
