<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter_text-filter-phone</name>
   <tag></tag>
   <elementGuidId>f40d6f3c-7664-4475-b725-f7cc65c79fa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text-filter-phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text-filter-phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>819a3b8a-8ff1-419c-b024-f01698a79376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pull-right</value>
      <webElementGuid>1b7ebc09-26fd-491f-8a72-252f6cb9c3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text-filter-phone</value>
      <webElementGuid>f040c739-8c6c-4c90-b523-a4ab89992e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71e39de5-6cf2-4811-8771-f51117adcca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-filter-phone&quot;)</value>
      <webElementGuid>7b45920f-a8c9-4340-9cbc-2620f1385a35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text-filter-phone']</value>
      <webElementGuid>f20dffe4-73cb-4952-b34b-1f8eebbfc4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bp-filters-navbar']/ul/li[2]/div/div/div/input</value>
      <webElementGuid>deec5a11-64c9-4587-991a-1d7aa42b6bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/input</value>
      <webElementGuid>7b8f6e27-26c5-4bff-8867-e78bbaa540da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'text-filter-phone' and @type = 'text']</value>
      <webElementGuid>e1d809d6-df5e-496e-a5de-290c8b53f539</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
