<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lanjut_1</name>
   <tag></tag>
   <elementGuidId>67b7d75e-9b0d-41a8-95e8-3f3e379fba91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[2]/div[2]/div/div[2]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.v-btn.v-btn--block.v-theme--light.v-btn--density-default.v-btn--size-default.v-btn--variant-flat.bg-primary-500.rounded-lg.color-neutral-10.text-capitalize.my-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>236de1e9-5218-4d2e-83fa-fe5fa5d5bedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c3815ed2-07a2-440e-87e1-68cd033ecd09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn v-btn--block v-theme--light v-btn--density-default v-btn--size-default v-btn--variant-flat bg-primary-500 rounded-lg color-neutral-10 text-capitalize my-2</value>
      <webElementGuid>25ce138f-7e53-46d5-bbf9-ee55fb613663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjut</value>
      <webElementGuid>7836561d-d285-4750-9c31-7cb2d419931d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fw_1704181635678&quot;)/div[@class=&quot;wizard-card-footer clearfix&quot;]/div[@class=&quot;wizard-footer-right full&quot;]/button[@class=&quot;v-btn v-btn--block v-theme--light v-btn--density-default v-btn--size-default v-btn--variant-flat bg-primary-500 rounded-lg color-neutral-10 text-capitalize my-2&quot;]</value>
      <webElementGuid>258aabba-f93a-43e1-b644-b463a27619aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>095f95ca-5eb5-4a2d-8778-f2d7c409cc3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fw_1704181635678']/div[2]/div[2]/button</value>
      <webElementGuid>011322c9-0afd-43e5-9ed0-ef575fad07ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>9ddaceb8-5433-4b1a-96ac-f75a947d562d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Lanjut' or . = 'Lanjut')]</value>
      <webElementGuid>17bfa0af-c636-4c49-8a31-8b3697fd03bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
