<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>eb29e5c1-7e7f-4ada-9348-4f938f255325</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.v-btn.v-btn--block.v-theme--light.v-btn--density-default.v-btn--size-default.v-btn--variant-flat.bg-primary-500.mt-2.rounded-lg.text-capitalize.color-neutral-10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca9c9f49-b501-4057-a2c4-ac6e48578a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c3b2ee7d-fe9d-461f-b395-bbc5137efd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn v-btn--block v-theme--light v-btn--density-default v-btn--size-default v-btn--variant-flat bg-primary-500 mt-2 rounded-lg text-capitalize color-neutral-10</value>
      <webElementGuid>752210eb-51c5-4d82-a3e5-b4e3c778b1a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Masuk </value>
      <webElementGuid>b54ac3e6-cc13-40e3-9d65-35353b232103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-container&quot;]/div[@class=&quot;v-responsive&quot;]/div[@class=&quot;v-responsive__content&quot;]/div[@class=&quot;px-5 px-lg-0&quot;]/form[@class=&quot;v-form my-10&quot;]/button[@class=&quot;v-btn v-btn--block v-theme--light v-btn--density-default v-btn--size-default v-btn--variant-flat bg-primary-500 mt-2 rounded-lg text-capitalize color-neutral-10&quot;]</value>
      <webElementGuid>750e78d4-6433-47fe-9f00-099f86c02737</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>fc3cb9cd-1514-4eed-915f-513438ff719c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/form/button</value>
      <webElementGuid>f3eaf7cd-04b5-4d08-b7bc-7d238c090896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f9c28743-3cbb-4207-b835-6e8cefc02fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Masuk ' or . = ' Masuk ')]</value>
      <webElementGuid>57b2a631-efea-4740-8bab-7c863bb9f84b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
