<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lanjut (1)</name>
   <tag></tag>
   <elementGuidId>5ce2537e-68dc-46e8-9698-9e7c6412a9a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.v-btn.v-btn--block.v-theme--light.v-btn--density-default.v-btn--size-default.v-btn--variant-flat.mt-2.rounded-lg.text-capitalize.bg-primary-500.color-neutral-10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a49552d-c12f-4c1d-8926-dbd0e59eb9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>38e87dcf-7612-4129-b8de-e59b8d67517e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn v-btn--block v-theme--light v-btn--density-default v-btn--size-default v-btn--variant-flat mt-2 rounded-lg text-capitalize bg-primary-500 color-neutral-10</value>
      <webElementGuid>e4b40c81-b838-476c-a676-34d8ed565f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjut</value>
      <webElementGuid>8e9019c7-6d12-4c30-a8ee-eadb6a71a8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-container&quot;]/div[@class=&quot;pa-5&quot;]/button[@class=&quot;v-btn v-btn--block v-theme--light v-btn--density-default v-btn--size-default v-btn--variant-flat mt-2 rounded-lg text-capitalize bg-primary-500 color-neutral-10&quot;]</value>
      <webElementGuid>43592f1f-a3c7-43b9-ab98-64f476ee1e69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>c994179e-6618-4361-b948-313d720bcdf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/button</value>
      <webElementGuid>15f44c5a-5112-4eaa-8a06-5ce8ac4f1054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>064aadae-f163-4ec2-a359-d7b7994f55ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Lanjut' or . = 'Lanjut')]</value>
      <webElementGuid>80d9c3f4-e62a-4f6c-97dc-f0dc9743bae4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
