<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lanjut</name>
   <tag></tag>
   <elementGuidId>9cdd4dc0-6aa5-43ab-887d-3ba93b35d128</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.v-btn.v-btn--block.v-theme--light.v-btn--density-default.v-btn--size-default.v-btn--variant-flat.bg-primary-500.mt-2.rounded-lg.text-capitalize.color-neutral-10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4cf2c745-0d6c-4c69-8515-8f5cd2c76cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>799a9415-8441-4413-ae8f-bec381f30b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn v-btn--block v-theme--light v-btn--density-default v-btn--size-default v-btn--variant-flat bg-primary-500 mt-2 rounded-lg text-capitalize color-neutral-10</value>
      <webElementGuid>50642178-37b9-489e-bbf0-4eb0eff54f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Lanjut </value>
      <webElementGuid>6f9b0cee-44a0-4e90-8681-eae740da7b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-container&quot;]/div[@class=&quot;v-responsive&quot;]/div[@class=&quot;v-responsive__content&quot;]/div[@class=&quot;text-center mt-10 px-10&quot;]/form[@class=&quot;v-form px-5 mt-5&quot;]/button[@class=&quot;v-btn v-btn--block v-theme--light v-btn--density-default v-btn--size-default v-btn--variant-flat bg-primary-500 mt-2 rounded-lg text-capitalize color-neutral-10&quot;]</value>
      <webElementGuid>ea5a76e4-3713-4d32-89bb-6e9651692fc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>ed0be58c-c38c-4051-b8a0-8dc59b6c7419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/form/button</value>
      <webElementGuid>7ee9447e-3215-4b20-8007-f163a97e0b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>db31e0cc-cef7-427f-888d-08b68abac3a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Lanjut ' or . = ' Lanjut ')]</value>
      <webElementGuid>7a141643-6e1c-4b54-83d3-9eb8c36d74a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
