<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Toko Kesehatan dan Kecantikan (Health  Beauty Shop)</name>
   <tag></tag>
   <elementGuidId>48d841cf-044d-4d74-a5a8-0575abcfd1db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-list-item.v-list-item--link.v-theme--light.v-list-item--density-default.v-list-item--3-line.v-list-item--variant-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2075bbdf-8853-4e7e-978c-cc1b30eeb0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item v-list-item--link v-theme--light v-list-item--density-default v-list-item--3-line v-list-item--variant-text</value>
      <webElementGuid>61f409d9-2cb0-477c-bbf3-f9ec3e63895d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0b95272d-4bb7-45df-8298-103669c26062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toko Kesehatan dan Kecantikan (Health &amp; Beauty Shop)</value>
      <webElementGuid>de257599-3314-41eb-92d2-f2e0e59ac344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[1]/div[@class=&quot;v-overlay-container&quot;]/div[@class=&quot;v-overlay v-overlay--absolute v-overlay--active v-theme--light v-locale--is-ltr v-menu&quot;]/div[@class=&quot;v-overlay__content v-autocomplete__content&quot;]/div[@class=&quot;v-list v-theme--light v-list--density-default v-list--one-line&quot;]/div[@class=&quot;v-list-item v-list-item--link v-theme--light v-list-item--density-default v-list-item--3-line v-list-item--variant-text&quot;]</value>
      <webElementGuid>5fe54984-cb58-42b9-b8e9-fcedcda6614a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>ae0dc70c-db36-4052-b756-3d878dd857f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Toko Kesehatan dan Kecantikan (Health &amp; Beauty Shop)' or . = 'Toko Kesehatan dan Kecantikan (Health &amp; Beauty Shop)')]</value>
      <webElementGuid>a47613e5-09e1-410e-a815-38db8f2c8688</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
