<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Omzet per Tahun_v-field__input</name>
   <tag></tag>
   <elementGuidId>854cea1e-02a7-4c87-8803-0d6aba2b2ac7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1']/div/form/div[8]/div/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>97620fe7-ea0f-415a-9bbc-00981ecb6aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>b086e405-8f04-4c91-a021-01b3201e8fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1&quot;)/div[@class=&quot;mt-5 px-1&quot;]/form[@class=&quot;v-form my-2&quot;]/div[@class=&quot;v-input v-input--horizontal v-input--density-default v-input--readonly v-text-field v-text-field--flush-details v-select v-select--single my-3&quot;]/div[@class=&quot;v-input__control&quot;]/div[@class=&quot;v-field v-field--active v-field--appended v-field--variant-underlined v-theme--light&quot;]/div[@class=&quot;v-field__field&quot;]/div[@class=&quot;v-field__input&quot;]</value>
      <webElementGuid>e4f45da0-cb76-45c8-8c3f-f75c778ad670</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div/form/div[8]/div/div/div[3]/div</value>
      <webElementGuid>de981d74-fcb2-419b-883a-2e1d97ee28af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[3]/div</value>
      <webElementGuid>919bc2df-658a-45b0-8643-66c1f61b3feb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
