<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_v-field__input_1</name>
   <tag></tag>
   <elementGuidId>ccb046cf-88be-4f16-a0e9-7b6c4c83ce79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1']/div/form/div[7]/div/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>955789de-200b-4467-afb4-974398cbeb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>4b09c94d-fa86-4643-86e9-a9967951fb98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1&quot;)/div[@class=&quot;mt-5 px-1&quot;]/form[@class=&quot;v-form my-2&quot;]/div[@class=&quot;v-input v-input--horizontal v-input--density-default v-input--readonly v-text-field v-text-field--flush-details v-select v-select--single my-3&quot;]/div[@class=&quot;v-input__control&quot;]/div[@class=&quot;v-field v-field--active v-field--appended v-field--variant-underlined v-theme--light&quot;]/div[@class=&quot;v-field__field&quot;]/div[@class=&quot;v-field__input&quot;]</value>
      <webElementGuid>17a12d78-da7a-4726-af5b-13c7fd6ebbed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div/form/div[7]/div/div/div[3]/div</value>
      <webElementGuid>4258c0f7-3323-4e6f-a063-e51891b0bcee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[3]/div</value>
      <webElementGuid>e3556d0f-24dc-45af-998d-f0d12931cfe2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
