<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_reCAPTCHA</name>
   <tag></tag>
   <elementGuidId>2ae6d4b7-50ea-4686-89dd-470120e59d19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-anchor-container']/div[4]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.rc-anchor-logo-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8e626e35-0413-4af7-8557-4234a39fbbbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-anchor-logo-text</value>
      <webElementGuid>e8d26c1c-3e7c-4f26-a0ba-ae515e7e4bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>f2925503-35fc-47fd-aedc-5bc056b61e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-anchor-container&quot;)/div[@class=&quot;rc-anchor-normal-footer&quot;]/div[@class=&quot;rc-anchor-logo-portrait&quot;]/div[@class=&quot;rc-anchor-logo-text&quot;]</value>
      <webElementGuid>86c5e695-23b5-468a-99b5-aa303582b11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_BATPay Merchant/iframe_Lupa Password_a-j1cejena593d</value>
      <webElementGuid>3dfaa2cf-2f2c-4c3a-a5f1-d988c5e96d86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-anchor-container']/div[4]/div/div[2]</value>
      <webElementGuid>7dfa120e-6798-4f90-ba7e-eb3e23b738be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]</value>
      <webElementGuid>7944d188-ea70-4e10-addf-135bd0961404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'reCAPTCHA' or . = 'reCAPTCHA')]</value>
      <webElementGuid>5bda6035-fc02-4c9e-ab1d-c15d90c2d47f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
