<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rp0</name>
   <tag></tag>
   <elementGuidId>b7bbeceb-f693-4de7-9d11-8e507615e17b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-row.py-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[2]/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9e566f95-f14f-4ce2-811f-b0da3cb6ef3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-row py-2</value>
      <webElementGuid>49624fa5-ac95-4824-81d9-c8814f8ae13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp0</value>
      <webElementGuid>dd6e5ede-3fed-4b29-a181-253723878ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-container px-lg-0&quot;]/div[@class=&quot;v-responsive&quot;]/div[@class=&quot;v-responsive__content&quot;]/div[@class=&quot;v-sheet v-theme--light&quot;]/div[@class=&quot;v-card v-theme--light v-card--density-default elevation-0 v-card--variant-elevated mx-5 rounded-lg bg-primary-500&quot;]/div[@class=&quot;pt-5 px-5 color-neutral-10&quot;]/div[@class=&quot;v-row py-2&quot;]</value>
      <webElementGuid>d0e3479d-3888-48d2-8b6c-f68768761ddb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>d21d23a9-1690-4756-bd10-efed8d9a8a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>6b32707c-ad0d-4c2f-8ade-6cb6d019c4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Rp0' or . = 'Rp0')]</value>
      <webElementGuid>03fbd871-867d-476f-89a9-ae9effc5a403</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
