<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kombinasi email dan password tidak sesuai</name>
   <tag></tag>
   <elementGuidId>6a05fa40-ba4c-42e0-b4f4-c1a98ac76754</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='email-messages']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-messages__message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c3be3d4-8b4b-4c68-961e-79e44b95de64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-messages__message</value>
      <webElementGuid>52d95480-7219-4496-8664-6e1da9d40c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kombinasi email dan password tidak sesuai</value>
      <webElementGuid>a8ed5f39-8612-44f6-a48d-386edadfe513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-messages&quot;)/div[@class=&quot;v-messages__message&quot;]</value>
      <webElementGuid>305a40af-62ef-4d2f-b832-c42627b7c8f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='email-messages']/div</value>
      <webElementGuid>efaebef3-4a29-4790-b8b7-e60b2a452c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div</value>
      <webElementGuid>ab881a44-1cbc-4d3b-b56f-deac13baacb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Kombinasi email dan password tidak sesuai' or . = 'Kombinasi email dan password tidak sesuai')]</value>
      <webElementGuid>f0f7460a-226f-47c8-9c47-d402efc02621</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
