<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_v-field__input</name>
   <tag></tag>
   <elementGuidId>5ac144db-6c90-4b0d-83a3-e21a5ade6590</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[2]/div[2]/div/div[1]/div[2]/div/div/form/div[6]/div/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-field__input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8922e248-d655-4e37-8ff6-1857b0eda17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>f031b5a7-4996-4dd1-a142-343eed9c060d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0&quot;)/div[@class=&quot;mt-5 px-1&quot;]/form[@class=&quot;v-form my-2&quot;]/div[@class=&quot;v-input v-input--horizontal v-input--density-default v-input--readonly v-text-field v-text-field--flush-details v-select v-select--single my-3&quot;]/div[@class=&quot;v-input__control&quot;]/div[@class=&quot;v-field v-field--active v-field--appended v-field--variant-underlined v-theme--light&quot;]/div[@class=&quot;v-field__field&quot;]/div[@class=&quot;v-field__input&quot;]</value>
      <webElementGuid>ab5964ba-4007-4296-8883-92a35369f759</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/form/div[6]/div/div/div[3]/div</value>
      <webElementGuid>6c92300e-4bb3-4d31-951d-2fbe9bb499de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div</value>
      <webElementGuid>aacf061f-f01e-45fe-a5ee-98c4cdad1958</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
