<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Lupa Password_a-j1cejena593d</name>
   <tag></tag>
   <elementGuidId>c06ececf-9256-4f6f-a018-006052203485</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-j1cejena593d']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-j1cejena593d&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5548730a-0046-4806-9f35-9af412c0d118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>0e02e6ac-61b4-487b-a4aa-c03bd2d36d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>26a6046a-f1ac-4dbf-9f39-90d1652b1a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>5dc4318b-c139-464c-99ac-aa9a6228702c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>bb4cbd9c-7075-4dcf-8abf-1438283456a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-j1cejena593d</value>
      <webElementGuid>9618dfe0-c640-4f3c-928b-129e08e394eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>192104ec-3d4a-4db1-8cfe-b6d5e81e5e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>8f5236bb-c0ed-4c7e-b4c2-913f25019772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>692e96c6-e1ab-49a7-92fa-d322be87ce24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdDUvgmAAAAAHw8y5ZJA3voeb7TLYOMZz1bWMQp&amp;co=aHR0cHM6Ly9zYi1iaXNuaXMuYmF0cGF5LmlkOjQ0Mw..&amp;hl=en&amp;v=-QbJqHfGOUB8nuVRLvzFLVed&amp;size=normal&amp;cb=vz5yaq65d63j</value>
      <webElementGuid>7f41128c-ce9f-4e8a-9e8a-25a88e881d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-container&quot;]/div[@class=&quot;v-responsive&quot;]/div[@class=&quot;v-responsive__content&quot;]/div[@class=&quot;px-5 px-lg-0&quot;]/form[@class=&quot;v-form my-10&quot;]/div[@class=&quot;my-5 d-flex justify-center&quot;]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>a21156a7-836d-46a9-b035-8afa2d34c448</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-j1cejena593d']</value>
      <webElementGuid>4d3da644-9a39-432c-b35a-1af2ac4dc65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/form/div[4]/div/div/div/iframe</value>
      <webElementGuid>92b57291-2925-47f9-a492-2214d3cf38a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>70d9f0c3-257d-44b2-9870-756e0e1dedf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-j1cejena593d' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdDUvgmAAAAAHw8y5ZJA3voeb7TLYOMZz1bWMQp&amp;co=aHR0cHM6Ly9zYi1iaXNuaXMuYmF0cGF5LmlkOjQ0Mw..&amp;hl=en&amp;v=-QbJqHfGOUB8nuVRLvzFLVed&amp;size=normal&amp;cb=vz5yaq65d63j']</value>
      <webElementGuid>a428b745-0427-42f9-b4c7-21472f9f7c35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
