<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Harap melakukan verifikasi reCAPTCHA_a-2g2vsk64hz7g</name>
   <tag></tag>
   <elementGuidId>6ff4721b-e031-4774-9234-15109e3470dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-2g2vsk64hz7g']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-2g2vsk64hz7g&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>733c75b2-458f-4ed3-a690-33a52e1ee4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>71a4b20f-62f5-4f5f-9a8b-e399723bc4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>b3a50780-0aa8-449b-992f-9c0b86b37927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>cebe3edd-e0f8-4c70-8889-765d034a8101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>6928fa66-4f11-4dad-9209-d5c5af7d3cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-2g2vsk64hz7g</value>
      <webElementGuid>a292fea3-2a2e-4ea9-a3f0-893657275b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>844dcd30-68c0-42b1-a87d-5093d0ff8f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>5806cd61-7cbb-478b-b11e-dbfbe6859be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>4c8e31ae-ba40-4a95-9c1d-f13503ca5911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdDUvgmAAAAAHw8y5ZJA3voeb7TLYOMZz1bWMQp&amp;co=aHR0cHM6Ly9zYi1iaXNuaXMuYmF0cGF5LmlkOjQ0Mw..&amp;hl=en&amp;v=-QbJqHfGOUB8nuVRLvzFLVed&amp;size=normal&amp;cb=qv2w2ev3j6yr</value>
      <webElementGuid>cc0ac815-34d1-4daf-ae35-1806627eaf9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-container&quot;]/div[@class=&quot;v-responsive&quot;]/div[@class=&quot;v-responsive__content&quot;]/div[@class=&quot;px-5 px-lg-0&quot;]/form[@class=&quot;v-form my-10&quot;]/div[@class=&quot;my-5 d-flex justify-center&quot;]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>dd25c786-472c-45ba-9373-8f8c48d56dca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-2g2vsk64hz7g']</value>
      <webElementGuid>0d229ed8-cd96-46f6-ae16-1f672aded21b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/form/div[5]/div/div/div/iframe</value>
      <webElementGuid>ea15808e-650c-46ad-b84e-fe089babdd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>e960d266-1d04-4a5e-a3bf-c02de82288e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-2g2vsk64hz7g' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdDUvgmAAAAAHw8y5ZJA3voeb7TLYOMZz1bWMQp&amp;co=aHR0cHM6Ly9zYi1iaXNuaXMuYmF0cGF5LmlkOjQ0Mw..&amp;hl=en&amp;v=-QbJqHfGOUB8nuVRLvzFLVed&amp;size=normal&amp;cb=qv2w2ev3j6yr']</value>
      <webElementGuid>756b3ec4-a637-4bb7-b954-520660b50df1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
