<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputbisnis_kategori_usaha</name>
   <tag></tag>
   <elementGuidId>3de4480c-f583-44e6-90b0-88df1c94f575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bisnis_kategori_usaha']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bisnis_kategori_usaha</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f9a664f-85fc-4de3-8a45-a3fb99912d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih bidang usaha</value>
      <webElementGuid>652ed4f6-2f68-49c3-9508-99dd96535ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a4220e9f-026d-4728-811b-952328304717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>656cd275-76aa-43e0-9c3b-ae6a511363fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bisnis_kategori_usaha</value>
      <webElementGuid>52cd1e51-3c3a-4dd9-93a7-e5cec45f0c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bisnis_kategori_usaha-messages</value>
      <webElementGuid>489c228e-8eca-42a4-b4f4-a279cbd570bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bisnis_kategori_usaha&quot;)</value>
      <webElementGuid>05e18d12-b7c6-4870-8a18-46fd222992ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bisnis_kategori_usaha']</value>
      <webElementGuid>298a441d-b2ca-4b9d-973e-31bfebef91d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div/form/div[6]/div/div/div[3]/div/input</value>
      <webElementGuid>8167d736-e17b-44cf-9db9-dacf05525874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[3]/div/input</value>
      <webElementGuid>4aa49301-8ef7-4ff7-9db6-2a8b0f57c4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Pilih bidang usaha' and @type = 'text' and @id = 'bisnis_kategori_usaha']</value>
      <webElementGuid>3a8585a5-242b-4546-a828-f6acb833405f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
