<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_bisnis_akta_perubahan_isupload_1</name>
   <tag></tag>
   <elementGuidId>5e1f5e6c-341f-464c-b1ed-aa232772691e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[2]/div[2]/div/div[1]/div[2]/div/div/form/div[17]/div[2]/div/div/div[2]/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-110</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84a0d7fe-5fe6-42ae-89f6-0d872d483363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-110</value>
      <webElementGuid>1d69278c-34a4-4d05-b002-5d5f263887de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7b2f0522-3637-45fc-9554-588a488f1b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>52823696-bd61-4404-ab10-bd8270f16aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bisnis_akta_perubahan_isupload</value>
      <webElementGuid>3ad8292d-f26d-4735-9191-48e726d1199e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0794b4a2-3534-489a-bd68-5d3ba7506690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-110&quot;)</value>
      <webElementGuid>b6d14d8a-9f13-471f-ac5a-be45901305ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-110']</value>
      <webElementGuid>911c7fa9-c236-4b37-9fdb-5b499a48510c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div/form/div[17]/div[2]/div/div/div[3]/div/div/input</value>
      <webElementGuid>c264a211-3b5e-4682-99d6-1ccd4c457f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>10a64c9b-a97f-4ac2-823f-07661fdd8074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-110' and @type = 'radio' and @name = 'bisnis_akta_perubahan_isupload']</value>
      <webElementGuid>5949fcab-5901-4f94-8f4e-95850bd9f2da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
