<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputbisnis_account_branch</name>
   <tag></tag>
   <elementGuidId>8871cca2-3110-4c31-b96d-2027f4cef80c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bisnis_account_branch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bisnis_account_branch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb414995-7bf2-46c4-b117-923aec9b4e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan cabang pembukaan rekening</value>
      <webElementGuid>b5254d98-205a-4455-a29e-c60c4637cefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bf51953c-5ead-4382-a939-57193780aac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c34c479-7303-4c6d-a515-5f3ecf98f3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bisnis_account_branch</value>
      <webElementGuid>3038017e-9010-42ae-84da-21a07e75265f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bisnis_account_branch-messages</value>
      <webElementGuid>d3bbd9b4-5a1b-40b4-b160-11cfaf64956d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>ab11f376-905c-47ae-8bb1-aa04fb0c2794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>338da819-76ae-415c-98b4-68691b1ff7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bisnis_account_branch&quot;)</value>
      <webElementGuid>746f000a-06e9-4259-92a4-60e263a867dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bisnis_account_branch']</value>
      <webElementGuid>c7beef31-6fa8-4a3a-b746-856231a186e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2']/div/form/div[4]/div/div/div[3]/input</value>
      <webElementGuid>1c0d46cb-768c-4b21-8251-08a0a5ca556d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/input</value>
      <webElementGuid>73f69131-4318-458e-b5c3-c76c7d16c1a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukkan cabang pembukaan rekening' and @type = 'text' and @id = 'bisnis_account_branch']</value>
      <webElementGuid>efb15dea-6ab0-45a1-8e06-d191b02b96d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
