<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputbisnis_district_id</name>
   <tag></tag>
   <elementGuidId>480f6bed-1539-4bc6-af4e-aeecc2b2917b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bisnis_district_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bisnis_district_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8283bcef-40b0-4f0f-af82-cfc5620337df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih kecamatan</value>
      <webElementGuid>cecc6853-af94-4b4b-9e1d-d3486e0345af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d95c14e0-2a9c-48b3-9d9a-d1960acac265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aaefe0d5-1a01-4497-9dad-680cb687f300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bisnis_district_id</value>
      <webElementGuid>f77bd7e1-76ff-4c6d-838b-c7ab1e65f9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bisnis_district_id-messages</value>
      <webElementGuid>d1427589-fac9-490e-bc88-c3414cea0269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bisnis_district_id&quot;)</value>
      <webElementGuid>8e0803c8-7252-404a-9a64-5c8897c7182b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bisnis_district_id']</value>
      <webElementGuid>84a4e2fc-8fb3-492a-9e56-eb09abf19734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div/form/div[10]/div/div/div[3]/div/input</value>
      <webElementGuid>2fe03a19-ddea-4e92-bc45-d25c7e12b81b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[3]/div/input</value>
      <webElementGuid>5de2aaf0-3621-404e-bccb-e7cc3d355d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Pilih kecamatan' and @type = 'text' and @id = 'bisnis_district_id']</value>
      <webElementGuid>305ec168-2fd6-4fdd-95c4-c7fa6dc8641e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
