<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputbisnis_province_id</name>
   <tag></tag>
   <elementGuidId>fd91be23-438a-4c70-b1c5-270eda9044b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bisnis_province_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bisnis_province_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4efa0798-a3ff-4c16-8845-aefe97d91954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih provinsi</value>
      <webElementGuid>d8521532-6654-45d0-8b77-9057758b5def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7ca9d07b-9df6-4ec7-8491-a86e223a0712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58a2a4ab-eb14-49e9-a572-c95640941478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bisnis_province_id</value>
      <webElementGuid>99f154c7-5cb8-4b92-a661-85067ed0de1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bisnis_province_id-messages</value>
      <webElementGuid>28815a57-b312-4292-b556-ffbb895763a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bisnis_province_id&quot;)</value>
      <webElementGuid>662ae929-0449-4772-ab80-29a35097ae79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bisnis_province_id']</value>
      <webElementGuid>df6b824d-90a3-45c4-b2b2-5d54fcd079c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div/form/div[8]/div/div/div[3]/div/input</value>
      <webElementGuid>e9d70ec2-99bc-459f-84ca-6aa8d3573203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[3]/div/input</value>
      <webElementGuid>d3b2aa52-a52c-47a4-93be-b5b0c591082f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Pilih provinsi' and @type = 'text' and @id = 'bisnis_province_id']</value>
      <webElementGuid>10bdb60a-5625-4c31-9bf3-a04795a69f33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
