<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputbisnis_postal_code</name>
   <tag></tag>
   <elementGuidId>cba39c22-fc0f-4172-9211-7bc465994ca5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bisnis_postal_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bisnis_postal_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d61aba1-97e7-45c2-b600-46672e0eb46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih kode pos</value>
      <webElementGuid>811bb522-8f7b-4ffb-b542-55b6b08d7cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a58f6147-16f4-4a5e-80bd-52716e37c8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b254d518-13df-4d3a-bd8f-bde3ec5e3ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bisnis_postal_code</value>
      <webElementGuid>9aabfc98-1fe7-4784-bc06-55ddf0d5ad5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bisnis_postal_code-messages</value>
      <webElementGuid>0934d566-a155-4927-9d78-65542226535d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bisnis_postal_code&quot;)</value>
      <webElementGuid>1d3e295e-0ca6-45db-8d25-996fe7934578</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bisnis_postal_code']</value>
      <webElementGuid>f89386fc-77ce-4c59-8895-df8dc022a8d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div/form/div[12]/div/div/div[3]/div/input</value>
      <webElementGuid>82015be5-f070-4f8d-80f9-dabd1ce1063f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div[3]/div/input</value>
      <webElementGuid>3b7dd935-1d76-4eb6-94a1-28d260eb1c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Pilih kode pos' and @type = 'text' and @id = 'bisnis_postal_code']</value>
      <webElementGuid>b7b73058-1bab-4830-8ef1-5717a0dd8e96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
