<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_bisnis_nib_siup_isupload</name>
   <tag></tag>
   <elementGuidId>753a513f-764f-4fd4-9e89-011dc56bdd4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-114']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-114</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f63832b-52ae-4d9b-ac61-bc3e5fdc93e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-114</value>
      <webElementGuid>f973c931-cf1d-47f6-82f3-6fb2026be947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>543313e2-2f41-4779-991c-01fda9bf1f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c6f07552-be93-44cd-841a-64ac2e958f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bisnis_nib_siup_isupload</value>
      <webElementGuid>178f360f-82fe-463d-881e-d6a77d4fe70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>85c4bac4-d24e-4a26-ba0a-4a4ea3781dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-114&quot;)</value>
      <webElementGuid>2059fcd2-6245-4414-95c8-8997e2f85704</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-114']</value>
      <webElementGuid>e87b1540-dc7f-4f33-b614-8d7c1aa1a9ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div/form/div[17]/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>3a36bb93-8c21-40aa-9554-119cb72f406b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>7071901a-fabb-4416-9b71-338af1f3d60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-114' and @type = 'radio' and @name = 'bisnis_nib_siup_isupload']</value>
      <webElementGuid>319dc6f9-7a01-4ecd-add9-fbfa3fa9bcac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
