<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputbisnis_village_id</name>
   <tag></tag>
   <elementGuidId>dfd4a91e-8904-4cec-87ce-f66b434bac12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bisnis_village_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bisnis_village_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91d03c94-ae1b-4c65-ba89-890ac5023464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih desa</value>
      <webElementGuid>0d815fcd-ebbe-4ac1-8f3c-556ba0def67e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>acbf9242-4a54-4a3e-8a5d-f588a914b968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd12db67-5df2-4e7c-9ca2-2b7653b15102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bisnis_village_id</value>
      <webElementGuid>1246cba2-0cc0-4239-8ed0-a5875b4cebee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bisnis_village_id-messages</value>
      <webElementGuid>b32828c0-beb3-4133-8a76-7bba6c8842c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bisnis_village_id&quot;)</value>
      <webElementGuid>e17d6a7d-d232-42d8-a598-9ee0c7122f1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bisnis_village_id']</value>
      <webElementGuid>8225e087-2d35-4e14-824a-9de369233805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div/form/div[11]/div/div/div[3]/div/input</value>
      <webElementGuid>497eab5d-9d5f-463d-8795-f3cc8a58e504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[3]/div/input</value>
      <webElementGuid>6754647e-928b-4a0d-9fd0-152891a84437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Pilih desa' and @type = 'text' and @id = 'bisnis_village_id']</value>
      <webElementGuid>7b662619-042b-4d34-afe1-96ca293e07f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
