<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputinput-123</name>
   <tag></tag>
   <elementGuidId>5edf176f-182a-4ee6-84ac-20b9d024a897</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[2]/div[2]/div/div[1]/div[2]/div/div/form/div[1]/div/div/div[3]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-123</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49fce857-e7c8-4588-8bc8-43f520620734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih bank</value>
      <webElementGuid>ad7380ad-309b-400a-a57d-66c56e555b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>50cf762a-ee9f-4f54-a35d-9d53998ffe91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b57de1c5-f9d2-45f0-8334-56b374ab489a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-123</value>
      <webElementGuid>93cb00f3-e9db-4b1c-ad59-e89f4a977860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>input-123-messages</value>
      <webElementGuid>00c1130b-bdc8-41c8-a648-2c0968662076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-123&quot;)</value>
      <webElementGuid>95ed6ee3-3ed5-4923-b263-16d7f77bea43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-123']</value>
      <webElementGuid>e70a970d-87e5-4b46-9186-1631f49fd2eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2']/div/form/div/div/div/div[3]/div/input</value>
      <webElementGuid>15911aef-5067-4187-a1e3-061cd69aac78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a1b963d9-9340-489b-a07f-d8972be4c303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Pilih bank' and @type = 'text' and @id = 'input-123']</value>
      <webElementGuid>c92bc1b5-e747-42c3-aab5-fecef15fc85a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
