<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputbisnis_merchant_email</name>
   <tag></tag>
   <elementGuidId>a6554d9b-238a-49e2-9281-e261dcfd0e8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bisnis_merchant_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bisnis_merchant_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb9df2ec-306f-4d1e-a2a9-03a71e818042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: namausaha@mail.com</value>
      <webElementGuid>0d58f0fd-cd69-44b7-82e9-14d48a95aad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7b0d2960-5f1a-43b5-ad61-941249a00329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ecedccbe-0e7c-465f-ac03-f8bb0be4eab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bisnis_merchant_email</value>
      <webElementGuid>e298c3f1-a493-4db5-b3ea-91a5b83f0d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bisnis_merchant_email-messages</value>
      <webElementGuid>0d7e00d0-2274-474b-8738-17666978dff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>69727751-d54e-475a-ad57-b6fb4765be93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>eeeb94b1-348d-4c0e-9bfd-effa60bcf250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bisnis_merchant_email&quot;)</value>
      <webElementGuid>0cde9356-89d7-40be-a610-ba2d447fce3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bisnis_merchant_email']</value>
      <webElementGuid>2413bf55-7b27-429c-8a0a-c14ca9d59045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div/form/div[14]/div/div/div[3]/input</value>
      <webElementGuid>da597f8e-afa9-40aa-b17d-15695ac2a5d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div[3]/input</value>
      <webElementGuid>7da53fd4-b911-4627-af76-5b66dcdbc5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Contoh: namausaha@mail.com' and @type = 'text' and @id = 'bisnis_merchant_email']</value>
      <webElementGuid>0a521791-4469-4d9d-8f3b-dc5854f21955</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
