<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_bisnis_jenis_usaha</name>
   <tag></tag>
   <elementGuidId>eb333c61-85d0-4344-b1e2-b7f9b21774b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-65']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-65</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab32264c-a47d-4186-a2be-6a92aaa87bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-65</value>
      <webElementGuid>1d9d2a6c-79ce-436a-be97-4d6a1563ceaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>18a9873d-2d09-4520-899f-1a7c359715c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c88c3a1a-7a0a-4cc9-8134-fd6a96e372fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bisnis_jenis_usaha</value>
      <webElementGuid>f433ee33-a1d4-4458-9cb3-5d5ef1428d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>online</value>
      <webElementGuid>cc3b87a0-b23f-4de2-b82e-1d2e23f09159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-65&quot;)</value>
      <webElementGuid>6c058d25-47e9-45bf-a39d-2a6e07c36edd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-65']</value>
      <webElementGuid>8c0b4710-7e95-4ac6-bfaf-bec159831829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div/form/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>475985f7-7a2c-4484-b84b-54ac296838de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/input</value>
      <webElementGuid>205aadd7-0cbf-4a1d-9f16-c6148c68c01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-65' and @type = 'radio' and @name = 'bisnis_jenis_usaha']</value>
      <webElementGuid>9a84f731-9b52-4448-8864-ed457f3ee227</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
