<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NPWP Perusahaan_bisnis_npwp_file</name>
   <tag></tag>
   <elementGuidId>f1f75315-b968-45b5-8ba5-ad66e0af9d2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bisnis_npwp_file']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bisnis_npwp_file</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77bd10c1-781c-47f2-86c5-d9a1c0b56883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>df9a25d6-25a4-45cf-8c43-f047de181b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bisnis_npwp_file</value>
      <webElementGuid>9e19a280-4b0b-4925-874e-7d2ab799b7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bisnis_npwp_file-messages</value>
      <webElementGuid>d703d5e9-e695-4a84-b80d-2be9b4f3efa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bisnis_npwp_file&quot;)</value>
      <webElementGuid>a467c877-b357-46a9-9729-124877345408</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bisnis_npwp_file']</value>
      <webElementGuid>3febe5f9-ad9e-4265-ac8d-aa530c25ab22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/form/div[7]/div/div/div/div[4]/input</value>
      <webElementGuid>5dee9d84-9dbd-49ec-b90c-fea68d7a652c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>8967f287-4337-44a6-930d-9ab4df42013c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'bisnis_npwp_file']</value>
      <webElementGuid>46e564f0-f715-4d4b-b170-7050891bc890</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
