<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputbisnis_city_id</name>
   <tag></tag>
   <elementGuidId>702be10a-20c0-4b7d-9615-aff657436851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bisnis_city_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bisnis_city_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b628ae77-7c45-4deb-bbd3-2cf1c56a7f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih kota/kabupaten</value>
      <webElementGuid>dc3bc103-0897-4c07-97bb-391d8465db84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f1d5b61c-6b9d-4dd0-ae5e-b612cde6c6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0dbd2a8a-9596-47d2-ae81-c01ed8148db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bisnis_city_id</value>
      <webElementGuid>e5a2f575-b889-429e-9574-aa6d3bb4ad06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bisnis_city_id-messages</value>
      <webElementGuid>6b829c45-b501-47e3-ba1b-65d09f39053e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bisnis_city_id&quot;)</value>
      <webElementGuid>512121ce-bc73-4700-85f2-b701a4e87b1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bisnis_city_id']</value>
      <webElementGuid>0d15ede0-d959-412a-80dd-ecae35cb5b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div/form/div[9]/div/div/div[3]/div/input</value>
      <webElementGuid>41d0a0d9-0da1-41a8-8de5-cc7fa4543bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[3]/div/input</value>
      <webElementGuid>7723dcff-6dc8-4c90-bded-cbb6e2cde23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Pilih kota/kabupaten' and @type = 'text' and @id = 'bisnis_city_id']</value>
      <webElementGuid>09fc59f3-f25a-4dff-817f-365c22c37ce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
