<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Masukkan kode OTP yang sudah kami kirimkan ke email aqilayopmail.com</name>
   <tag></tag>
   <elementGuidId>8338953d-2da9-4c14-8ae2-b66dc3b447fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[2]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.text-body-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a19821c5-1b56-45e5-bd06-2c1478e2cfc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-body-2</value>
      <webElementGuid>d6d71f61-366a-4245-ab1e-ad8ece9edbf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masukkan kode OTP yang sudah kami kirimkan ke email aqila@yopmail.com</value>
      <webElementGuid>06bb2c1b-7ca7-4367-bb42-131c1228d43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-container&quot;]/div[@class=&quot;v-responsive&quot;]/div[@class=&quot;v-responsive__content&quot;]/div[@class=&quot;text-center mt-10&quot;]/span[@class=&quot;text-body-2&quot;]</value>
      <webElementGuid>41c89469-bf9d-403a-ae3d-c0786265fa91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/span</value>
      <webElementGuid>f3582d9c-64b3-4f8f-a6d7-a828d5e66556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>ab3357f7-1d55-400b-8082-01f0e5124903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Masukkan kode OTP yang sudah kami kirimkan ke email aqila@yopmail.com' or . = 'Masukkan kode OTP yang sudah kami kirimkan ke email aqila@yopmail.com')]</value>
      <webElementGuid>26bdc89a-73b6-404e-bc58-77da23a3b277</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
