<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Daftar</name>
   <tag></tag>
   <elementGuidId>a0753b0a-b1d9-4ddf-a40c-ac811d5f0a2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text-body-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[2]/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>55c48acc-9e1a-417c-b687-90aaedb8a4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-body-2</value>
      <webElementGuid>fd4f0788-6f38-41d7-8a30-9b450a14f1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>c6a08204-1e3a-44eb-8afa-af7f6ea8ea1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-container px-lg-0&quot;]/div[@class=&quot;v-responsive&quot;]/div[@class=&quot;v-responsive__content&quot;]/div[@class=&quot;v-sheet v-theme--light&quot;]/div[@class=&quot;d-flex justify-space-between px-5 my-5&quot;]/a[1]/span[@class=&quot;text-body-2&quot;]</value>
      <webElementGuid>2a8c5683-102e-482c-9549-61b6a99ada94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/a/span</value>
      <webElementGuid>85b6d6c2-f543-44e3-86ba-5b859c2635b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>e968e946-45ae-4619-870b-784c33680139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>f5be3872-dce6-40d2-ae7f-d1ac04cd2e4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
