<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareapemilik_owner_name</name>
   <tag></tag>
   <elementGuidId>fd4b6d34-4e8f-4113-9765-cb47d66643d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='pemilik_owner_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pemilik_owner_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>568f8d00-e5ec-4512-84e2-1791a54af110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>dc0f73ed-cc8b-4cff-ae00-17f168def49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Ananda Salma</value>
      <webElementGuid>3f62e4a9-76bc-47c8-8567-67bc5e7b8350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>78dbe78b-dad8-4017-819e-cec2c6d1b5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pemilik_owner_name</value>
      <webElementGuid>f571db74-dde5-4b2e-85e4-eae8cdee9de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>pemilik_owner_name-messages</value>
      <webElementGuid>6df1a9e8-16b8-439e-bb62-cf9d8c94a455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>46fccdd8-6bd3-49f0-a691-50ce49c0d939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>e9111162-6494-408d-a8b5-9ed4e0b849d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pemilik_owner_name&quot;)</value>
      <webElementGuid>2a9fe061-f890-4201-9212-efd94e53416b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='pemilik_owner_name']</value>
      <webElementGuid>083ec67b-39a9-4ed3-89ac-4e531465c98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/form/div/div/div/div[3]/textarea</value>
      <webElementGuid>66068537-0d9a-43b8-a4c4-5e253a078b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>79f38155-3811-42cc-af6a-2b95d340abdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Contoh: Ananda Salma' and @id = 'pemilik_owner_name' and @type = 'text']</value>
      <webElementGuid>6417609e-e564-4518-bac5-ddd5a827652d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
