<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareabisnis_alamat_usaha</name>
   <tag></tag>
   <elementGuidId>ac33903b-5aec-46cb-a2c4-5aac36dfdd91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='bisnis_alamat_usaha']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bisnis_alamat_usaha</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>830e42dd-ac64-4c3c-a70a-aea0c5e3258c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>f1d36955-226f-48ba-9dbc-5c4ecf511039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Sebutkan nama jalan, nomor, RT/RW</value>
      <webElementGuid>e6637b30-2d86-43d4-94d8-e493324694c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>17cb195b-234d-430f-869f-416b3d33370f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bisnis_alamat_usaha</value>
      <webElementGuid>2cd4d1af-61b3-4f4b-ab35-643c6a6f8c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bisnis_alamat_usaha-messages</value>
      <webElementGuid>889ef864-b067-4b04-b679-83715f22c34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10f7f6f4-1710-48b2-ae44-6a61922fd6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>23cbb0fe-9522-420d-8bda-611cafd0ca97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bisnis_alamat_usaha&quot;)</value>
      <webElementGuid>0561e5d7-dc64-4d98-91fd-b38c59dce2d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='bisnis_alamat_usaha']</value>
      <webElementGuid>5145ac89-bd86-49d2-a48c-f172f861ef6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div/form/div[13]/div/div/div[3]/textarea</value>
      <webElementGuid>291fb635-644d-420c-b075-10094ce43002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div[3]/textarea</value>
      <webElementGuid>f23be5a3-1e67-45c0-9177-f86d3fbae338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Sebutkan nama jalan, nomor, RT/RW' and @id = 'bisnis_alamat_usaha' and @type = 'text']</value>
      <webElementGuid>3bba1a59-96db-4fe0-965b-045b6175efae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
