<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareabisnis_nama_usaha</name>
   <tag></tag>
   <elementGuidId>f9765586-9c7a-429d-82d8-b3193cbe8975</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='bisnis_nama_usaha']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bisnis_nama_usaha</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>79a6f200-ed0f-4706-8b89-05ac072b412e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>1fc45119-62d0-4e36-a1b8-0e1640308f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Jogjakustik</value>
      <webElementGuid>3a9ea2f1-4981-4274-8bb2-71440356cfe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>87442963-c72e-4547-81fa-d2a768ff5787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bisnis_nama_usaha</value>
      <webElementGuid>9505e8aa-7228-48fb-a564-1c1e902020b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bisnis_nama_usaha-messages</value>
      <webElementGuid>15eb33df-302a-4def-9e81-b19e3534997c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6680d5e9-0acb-4e4e-bf38-c18b3d606522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>b9aabbfe-9aea-4bbe-afcf-14a62f44cb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bisnis_nama_usaha&quot;)</value>
      <webElementGuid>fc9e4b47-bbbe-4507-8549-afe8d518501d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='bisnis_nama_usaha']</value>
      <webElementGuid>bf005e27-aba1-4b47-a646-5d9f6d03f834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div/form/div[4]/div/div/div[3]/textarea</value>
      <webElementGuid>01c84a34-160f-4f93-9ce8-f81a504ea6b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/textarea</value>
      <webElementGuid>32f3d5c1-dae8-4599-9ec9-e8fa482d987d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Contoh: Jogjakustik' and @id = 'bisnis_nama_usaha' and @type = 'text']</value>
      <webElementGuid>6611d0c0-bba5-4ea3-944b-a01fd9f71b26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
