<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareapemilik_jabatan</name>
   <tag></tag>
   <elementGuidId>71c9bd8d-4773-41e3-99c8-db01bb52ed24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='pemilik_jabatan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pemilik_jabatan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1ad82b11-a8fa-4f84-a1b6-582396f12f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>73916e8f-cd9b-4da7-8947-b6e54fd3fac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Manager Marketing</value>
      <webElementGuid>32a72fd8-a10b-4915-9f8b-ea50f9563363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8ff57d1c-b409-49d7-87a6-7d8a69db53a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pemilik_jabatan</value>
      <webElementGuid>5af8f7e9-7682-4c28-ae9e-f86e6bea9965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>pemilik_jabatan-messages</value>
      <webElementGuid>a3cb1b4b-c4a1-4d05-9ca8-6f0516775e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a5539d10-6809-4fbf-9abe-76115b7ba2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>481f8ef1-4f10-42c0-a35a-8c6d7a18ae1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pemilik_jabatan&quot;)</value>
      <webElementGuid>d7737d07-17c7-4a99-916c-26db87835066</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='pemilik_jabatan']</value>
      <webElementGuid>9e164a9a-6a83-48e2-99ed-68e3c7bc0fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/form/div[2]/div/div/div[3]/textarea</value>
      <webElementGuid>96f1dd98-63d9-47d8-b9fb-7fede2ea89be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/textarea</value>
      <webElementGuid>f6c7ba3c-1285-4589-ada2-883eb45e2f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Contoh: Manager Marketing' and @id = 'pemilik_jabatan' and @type = 'text']</value>
      <webElementGuid>79918f9f-fb9c-4ca1-86e0-c755b972c87d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
