<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lihat</name>
   <tag></tag>
   <elementGuidId>a9e66c3b-88ec-492e-b451-9e64e9fd2155</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='crudTable']/tbody/tr/td[8]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-sm.btn-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5bfe2ad2-ca67-496f-b5f7-d4229e779d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sb-batpanel.batpay.id/customer/27/show</value>
      <webElementGuid>3e1f6197-445f-4cf8-afe6-5d1dc84e773e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-link</value>
      <webElementGuid>100db137-97c9-42f8-bf9f-d56287fd9e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Lihat</value>
      <webElementGuid>35aa03e6-5654-4fab-918c-6d1c6506f54e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;crudTable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[8]/a[@class=&quot;btn btn-sm btn-link&quot;]</value>
      <webElementGuid>593830f5-252c-4de4-a139-2c95f8aeb11d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='crudTable']/tbody/tr/td[8]/a</value>
      <webElementGuid>3e75e1e7-40cc-4237-9855-732a14b27cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lihat')]</value>
      <webElementGuid>10d3ab2b-9d48-4446-8c98-4e32ddeed460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sb-batpanel.batpay.id/customer/27/show')]</value>
      <webElementGuid>0aee536b-25bb-414a-ad77-d9a58cca667d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a</value>
      <webElementGuid>9d1c9cf6-cd27-424f-926a-15181fa28a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sb-batpanel.batpay.id/customer/27/show' and (text() = ' Lihat' or . = ' Lihat')]</value>
      <webElementGuid>ba2b87e8-a864-4dc8-8f52-11a7de164924</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
