<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_premium</name>
   <tag></tag>
   <elementGuidId>c771f4db-7c3a-460b-ade9-438106477b7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bp-filters-navbar']/ul/li[4]/ul/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c72b9e6e-2660-414a-95a4-5d13368a3d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item active</value>
      <webElementGuid>8e7f0cac-1992-4a3a-ad61-9b29e204e8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameter</name>
      <type>Main</type>
      <value>membership</value>
      <webElementGuid>569e364c-8b0d-4840-833c-41460f9c4106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dropdownkey</name>
      <type>Main</type>
      <value>30ead9de-6301-4936-9837-f115307aeb3d</value>
      <webElementGuid>54e4cba3-3fdd-406f-9098-0abac99fbf7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>premium</value>
      <webElementGuid>3fe99557-5689-4c57-9994-51ca2d79192a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bp-filters-navbar&quot;)/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;nav-item dropdown active show&quot;]/ul[@class=&quot;dropdown-menu show&quot;]/a[@class=&quot;dropdown-item active&quot;]</value>
      <webElementGuid>4e37069b-4cad-4521-a360-dd4de6bf48ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bp-filters-navbar']/ul/li[4]/ul/a[3]</value>
      <webElementGuid>f55a87a7-a523-48fb-a572-ad52ac7b7f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'premium')]</value>
      <webElementGuid>43a00152-bb1f-4e91-bfa0-58b055aaf54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[56]</value>
      <webElementGuid>5d8e9c5f-cd02-4a2b-9b01-483e4da5a3cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>1f7b8257-5708-422b-bfc4-646cb59680e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'premium' or . = 'premium')]</value>
      <webElementGuid>47abd9d4-858e-42c7-a072-58991b0cf6dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
