<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter_text-filter-phone</name>
   <tag></tag>
   <elementGuidId>5c412f25-16f1-4c40-afb2-329b7b75df14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text-filter-phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text-filter-phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2028e231-1dbc-4db9-8f8d-67133fa2a7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pull-right</value>
      <webElementGuid>6f1bf8a5-e34b-4364-8677-6a24c27de213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text-filter-phone</value>
      <webElementGuid>22a3926b-c659-4118-932e-b42ed44a5525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b18c272-bd43-4d63-8740-c7fcca607884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-filter-phone&quot;)</value>
      <webElementGuid>4d8c3ece-3dad-46d5-917e-17b88035c864</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text-filter-phone']</value>
      <webElementGuid>f3fa16e1-d80f-4619-928f-bbb2a2549309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bp-filters-navbar']/ul/li[2]/div/div/div/input</value>
      <webElementGuid>97ac9239-3cfa-473c-81c5-45f0e5cce2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/input</value>
      <webElementGuid>b4eb066f-aab2-40ac-a7a7-83ac72f87a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'text-filter-phone' and @type = 'text']</value>
      <webElementGuid>199d0cad-62ce-4b1b-8205-491d5ae5b3e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
