<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pelanggan Aktif</name>
   <tag></tag>
   <elementGuidId>01f391a5-8790-4278-b8b3-50bcc1f3ff3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.text-capitalize</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d72647ea-ce65-4237-8a65-55f32df9b5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-capitalize</value>
      <webElementGuid>2c6dde44-73cc-48f6-972a-87d59658151a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pelanggan Aktif</value>
      <webElementGuid>23838b2a-411c-4aef-8bde-e53869ce08ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pace-done pace-done pace-running app aside-menu-fixed sidebar-lg-show&quot;]/div[@class=&quot;app-body&quot;]/main[@class=&quot;main pt-2&quot;]/div[@class=&quot;container-fluid&quot;]/h2[1]/span[@class=&quot;text-capitalize&quot;]</value>
      <webElementGuid>b7b35f93-5033-458c-8be9-3df57787c153</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/span</value>
      <webElementGuid>0f9cefd2-d73d-4dc9-8552-72be235ff69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pelanggan Aktif' or . = 'Pelanggan Aktif')]</value>
      <webElementGuid>a8e3b664-bd90-42ad-ae62-a476f71b6e2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
