<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter_text-filter-phone</name>
   <tag></tag>
   <elementGuidId>c62061d4-3ecb-4a56-822b-35e13dbda657</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text-filter-phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text-filter-phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b511dad8-35ec-49b4-b4cc-1eed83bef4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pull-right</value>
      <webElementGuid>15658f97-5f0a-4a09-9195-a0a562b35f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text-filter-phone</value>
      <webElementGuid>d271f831-964d-48d1-9472-27866fb8da1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bb982914-d59e-464c-9655-235b2465b583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-filter-phone&quot;)</value>
      <webElementGuid>59ef6191-7c3c-43db-9c4e-fca4002bf513</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text-filter-phone']</value>
      <webElementGuid>2b59da8a-ab7a-479d-b77f-0f6b12ac49dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bp-filters-navbar']/ul/li[2]/div/div/div/input</value>
      <webElementGuid>10efb726-dc38-4ced-ba28-2d2dac864a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/input</value>
      <webElementGuid>9434ec83-dae0-4eb7-bfc5-0abcedbca545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'text-filter-phone' and @type = 'text']</value>
      <webElementGuid>135e5e6d-1b3b-473e-a268-9f4bbc624ce7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
