<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lihat</name>
   <tag></tag>
   <elementGuidId>5c41aede-741f-4acd-bc8b-81dec47bc878</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-sm.btn-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='crudTable']/tbody/tr/td[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>99d0a318-f771-4be6-ad78-8bbe46f532a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sb-batpanel.batpay.id/premium-customer/65a5ea6c-87bc-4b56-a2f6-fd07efc42f7f/show</value>
      <webElementGuid>a005c296-4326-4f11-9a2e-9e2ef746aa64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-link</value>
      <webElementGuid>cee8f465-3b82-44f8-b53f-89d6e40bcd73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Lihat</value>
      <webElementGuid>a804235a-7cdd-4fc8-9d73-430989637660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;crudTable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[7]/a[@class=&quot;btn btn-sm btn-link&quot;]</value>
      <webElementGuid>9acdaef1-a807-4881-90f8-8edf60b86918</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='crudTable']/tbody/tr/td[7]/a</value>
      <webElementGuid>8902f26c-1ccd-469a-a663-8e523b548fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lihat')]</value>
      <webElementGuid>06295b11-f0e7-4f1e-bc40-54efd80dc3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sb-batpanel.batpay.id/premium-customer/65a5ea6c-87bc-4b56-a2f6-fd07efc42f7f/show')]</value>
      <webElementGuid>2c97df83-0b87-41c6-9707-c3e686894aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a</value>
      <webElementGuid>1f62f66d-f10a-447b-9a80-d46fe18847a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sb-batpanel.batpay.id/premium-customer/65a5ea6c-87bc-4b56-a2f6-fd07efc42f7f/show' and (text() = ' Lihat' or . = ' Lihat')]</value>
      <webElementGuid>ac0d4a9c-f41e-4ec2-9fc6-6f250606dc49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
