<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_urlTransfer</name>
   <tag></tag>
   <elementGuidId>f21e090c-6a5f-49aa-8cac-25a6ac8ae7d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='urlTransfer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;urlTransfer&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4dc0abea-808d-4ff7-a2ea-08781d69dc49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>3518fb98-46be-4ec5-a5ce-8a70ad5d14ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>urlTransfer</value>
      <webElementGuid>2351b92a-03bf-4f30-a649-6ec748ddc847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>urlTransfer</value>
      <webElementGuid>0318a3e0-8908-49a3-9ff3-318152855af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file_input backstrap-file-input</value>
      <webElementGuid>8514a093-c345-4dbd-85cc-96b483bb4062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pace-done pace-running app aside-menu-fixed sidebar-lg-show&quot;]/div[@class=&quot;app-body&quot;]/main[@class=&quot;main pt-2&quot;]/div[@class=&quot;container-fluid animated fadeIn&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 bold-labels&quot;]/form[1]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body row&quot;]/div[@class=&quot;form-group col-sm-12 required&quot;]/div[@class=&quot;backstrap-file&quot;]/input[@class=&quot;file_input backstrap-file-input&quot;]</value>
      <webElementGuid>2b1da2c0-6741-423c-9b65-e8a6036bf879</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='urlTransfer']</value>
      <webElementGuid>ae31b283-f223-4d54-a978-c234e87f90c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>96160034-88ce-4c23-b9e3-527a1ce7bcd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'urlTransfer']</value>
      <webElementGuid>c50f1cac-0913-4428-8f9c-913ffa9e7389</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
