<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. Referensi  No. Tiket_referenceNumber</name>
   <tag></tag>
   <elementGuidId>48662edf-dc9c-4efa-8561-f61a8942c4f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='referenceNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;referenceNumber&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82efead4-0fa9-413a-a32e-69578b989eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c5ea8c8-9652-4cdb-bd02-e7acfa0c465a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>referenceNumber</value>
      <webElementGuid>87cb7ee6-ac3f-47f6-8e5e-0ef9c784b4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan No. Referensi / No. Tiket</value>
      <webElementGuid>192f2558-6521-419b-9994-869b5e07d6c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>referenceNumber</value>
      <webElementGuid>10085d38-1cb6-46b7-8c3c-38f808a69009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fffd68f5-109c-435d-bfbe-62cdf8d00e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app aside-menu-fixed sidebar-lg-show&quot;]/div[@class=&quot;app-body&quot;]/main[@class=&quot;main pt-2&quot;]/div[@class=&quot;container-fluid animated fadeIn&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 bold-labels&quot;]/form[1]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body row&quot;]/div[@class=&quot;form-group col-sm-12 required&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>6c563d1d-ae10-40af-b3f1-5cef98df7959</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='referenceNumber']</value>
      <webElementGuid>a1f93b35-67ec-46e7-8afc-55ea7d97b167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>6bb1f490-e2d1-4c22-bc45-54c19eb8468b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'referenceNumber' and @placeholder = 'Masukkan No. Referensi / No. Tiket']</value>
      <webElementGuid>e3029af7-eab8-413c-9012-4e238cb3e9bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
