<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Lanjut</name>
   <tag></tag>
   <elementGuidId>ff7a4ec6-bfa4-4ba5-8b28-5e90ec51f59b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='label-btn-save']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#label-btn-save</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bf611ef0-df9f-4a9e-8a5a-2beb23e01810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>save_and_back</value>
      <webElementGuid>6f171365-bef8-45d2-80f8-43860dec50f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>label-btn-save</value>
      <webElementGuid>ff14ab09-c148-46a0-95ec-b260f7539a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjut</value>
      <webElementGuid>b7435fd3-6a35-4234-9e95-412d5cf6b145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;label-btn-save&quot;)</value>
      <webElementGuid>11e95dad-aeab-4a52-9621-1b47dee99984</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='label-btn-save']</value>
      <webElementGuid>4ecaf959-3717-42a7-94cc-827eef2ae1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btn-submit']/span</value>
      <webElementGuid>a9ff9c06-c457-4a1f-b9eb-2408e1700595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/span</value>
      <webElementGuid>b99950e1-217d-48f6-8c94-960f8b9bbe47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'label-btn-save' and (text() = 'Lanjut' or . = 'Lanjut')]</value>
      <webElementGuid>71a921fd-078c-4c15-8c63-6dbcd4102352</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
