<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_tolak</name>
   <tag></tag>
   <elementGuidId>cdf57b91-ab9f-4ce0-a462-cfcb41033b95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='approval-form']/div/div/div[3]/div[3]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>03d48df8-ac59-49d0-bd9c-fbd0e3c25d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tolak </value>
      <webElementGuid>59e5ad8c-9ad9-4580-a2d5-dd1160007ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;approval-form&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;note-editor note-frame panel panel-default&quot;]/div[@class=&quot;note-editing-area&quot;]/div[@class=&quot;note-editable&quot;]/p[1]</value>
      <webElementGuid>70dee2e4-6b17-482a-8d25-4f2c409a3af4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='approval-form']/div/div/div[3]/div[3]/p</value>
      <webElementGuid>21b8cfb9-3b9c-45b1-a020-d2e896214373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>060e42c0-6dd1-4da9-9cbc-2ffce6020bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'tolak ' or . = 'tolak ')]</value>
      <webElementGuid>f47837eb-907d-468e-91bd-cba14c582d8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
